version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: authority
  coins:
  - 20000iogov
  - 200000000iosgd
- name: bank1
  coins:
  - 100000000iosgd
- name: bank2
  coins:
  - 100000000iosgd
- name: bank3
  coins:
  - 100000000iosgd
- name: developer
  coins:
  - 20000iogov
  - 100000000iosgd
faucet:
  name: developer
  coins:
  - 5iogov
  - 100000iosgd
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    gov:
      deposit_params:
        min_deposit:
        - amount: "100000"
          denom: iogov
    staking:
      params:
        bond_denom: iosgd
    crisis:
      constant_fee:
        denom: iosgd
    mint:
      params:
        mint_denom: iosgd
  chain_id: io
validators:
# - name: authority
#   bonded: 60000000iosgd
# - name: bank1
#   bonded: 20000000iosgd
- name: bank2
  bonded: 30000000iosgd
- name: bank3
  bonded: 50000000iosgd